services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feed_a_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: